const products = [
  {
    id: 0,
    name: "Camiseta 1",
    image: "../../../public/product-thumb-1.jpeg",
    price: 49.9,
    category: "Camisetas",
    description: "Descrição da Camiseta 1",
  },
  {
    id: 1,
    name: "Calça 1",
    image: "../../../public/product-thumb-2.jpeg",
    price: 99.9,
    category: "Calças",
    description: "Descrição da Calça 1",
  },
  {
    id: 2,
    name: "Boné 1",
    image: "../../../public/product-thumb-3.jpeg",
    price: 29.9,
    category: "Bonés",
    description: "Descrição do Boné 1",
  },
  {
    id: 3,
    name: "Headphone 1",
    image: "../../../public/product-thumb-4.jpeg",
    price: 199.9,
    category: "Headphones",
    description: "Descrição do Headphone 1",
  },
  {
    id: 4,
    name: "Tênis 1",
    image: "../../../public/product-thumb-5.jpeg",
    price: 149.9,
    category: "Tênis",
    description: "Descrição do Tênis 1",
  },
  {
    id: 5,
    name: "Tênis 1",
    image: "../../../public/product-thumb-5.jpeg",
    price: 149.9,
    category: "Tênis",
    description: "Descrição do Tênis 1",
  },
  {
    id: 6,
    name: "Tênis 1",
    image: "../../../public/product-thumb-5.jpeg",
    price: 149.9,
    priceDiscount: 130.50,
    category: "Tênis",
    description: "Descrição do Tênis 1",
  },

  {
    id: 7,
    name: "Camiseta 1",
    image: "../../../public/product-thumb-1.jpeg",
    price: 49.9,
    category: "Camisetas",
    description: "Descrição da Camiseta 1",
  },
  {
    id: 8,
    name: "Calça 1",
    image: "../../../public/product-thumb-2.jpeg",
    price: 99.9,
    category: "Calças",
    description: "Descrição da Calça 1",
  },
  {
    id: 9,
    name: "Boné 1",
    image: "../../../public/product-thumb-3.jpeg",
    price: 29.9,
    category: "Bonés",
    description: "Descrição do Boné 1",
  },
  {
    id: 10,
    name: "Headphone 1",
    image: "../../../public/product-thumb-4.jpeg",
    price: 199.9,
    category: "Headphones",
    description: "Descrição do Headphone 1",
  },
  {
    id: 11,
    name: "Tênis 1",
    image: "../../../public/product-thumb-5.jpeg",
    price: 149.9,
    category: "Tênis",
    description: "Descrição do Tênis 1",
  },
  {
    id: 12,
    name: "Tênis 1",
    image: "../../../public/product-thumb-5.jpeg",
    price: 149.9,
    category: "Tênis",
    description: "Descrição do Tênis 1",
  },
  {
    id: 13,
    name: "Tênis 1",
    image: "../../../public/product-thumb-5.jpeg",
    price: 149.9,
    category: "Tênis",
    description: "Descrição do Tênis 1",
  },
];

export default products;
